### ISSUE TITLE
I/O error reading PNG header!

### ISSUE THREAD

**Issue by natros** [jonathanlermitage/IconViewer#1]
I'm getting this error with Icon Viewer 2 ver 1.3.0.193

IntelliJ IDEA 2020.3 Beta (Ultimate Edition)
Build #IU-203.5784.10, built on November 10, 2020
IntelliJ IDEA EAP User
Expiration date: December 10, 2020
Runtime version: 11.0.9+11-b1145.10 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.15.7
GC: ParNew, ConcurrentMarkSweep
Memory: 3987M
Cores: 16
Registry: debugger.valueTooltipAutoShowOnSelection=true, ide.mac.file.chooser.native=false
Non-Bundled Plugins: BrowseWordAtCaret, uk.co.ben-gibson.remote.repository.mapper, Builder Generator, GrepConsole, String Manipulation, YourKit Java Profiler 2020.9-b411 Integration, com.bruce.intellijplugin.generatesetter, org.mapstruct.intellij, com.intellij.plugins.watcher, com.sburlyaev.terminal.plugin, lermitage.intellij.iconviewer, Pythonid, com.baomidou.plugin.idea.mybatisx, com.intellij.gwt

From the logs, it seems is trying to load a `throbber.gif` as png 

`throbber.gif`
![throbber](https://user-images.githubusercontent.com/4996289/99378461-5b444f00-28bf-11eb-9af2-f5e93b2c11bf.gif)

```
2020-11-17 10:20:49,765 [ 942102]  ERROR - #com.intellij.util.ImageLoader - I/O error reading PNG header! 
javax.imageio.IIOException: I/O error reading PNG header!
	at java.desktop/com.sun.imageio.plugins.png.PNGImageReader.readHeader(PNGImageReader.java:315)
	at java.desktop/com.sun.imageio.plugins.png.PNGImageReader.readMetadata(PNGImageReader.java:698)
	at java.desktop/com.sun.imageio.plugins.png.PNGImageReader.readImage(PNGImageReader.java:1395)
	at java.desktop/com.sun.imageio.plugins.png.PNGImageReader.read(PNGImageReader.java:1810)
	at com.intellij.util.ImageLoader.loadPng(ImageLoader.java:368)
	at com.intellij.util.ImageLoader.loadFromStream(ImageLoader.java:563)
	at com.intellij.util.ImageLoader.loadFromBytes(ImageLoader.java:554)
	at lermitage.intellij.iconviewer.ImageIconProvider.previewImage(ImageIconProvider.java:82)
	at lermitage.intellij.iconviewer.ImageIconProvider.getIcon(ImageIconProvider.java:67)
	at com.intellij.util.PsiIconUtil.getProvidersIcon(PsiIconUtil.java:17)
	at com.intellij.psi.impl.ElementBase.doComputeIconNow(ElementBase.java:87)
	at com.intellij.psi.impl.ElementBase.lambda$computeIconNow$3(ElementBase.java:83)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:127)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:116)
	at com.intellij.psi.impl.ElementBase.computeIconNow(ElementBase.java:83)
	at com.intellij.psi.impl.ElementBase.lambda$static$0(ElementBase.java:43)
	at com.intellij.ui.DeferredIconImpl.evaluate(DeferredIconImpl.java:282)
	at com.intellij.ui.DeferredIconImpl.lambda$scheduleEvaluation$1(DeferredIconImpl.java:169)
	at com.intellij.ui.IconDeferrerImpl.evaluateDeferred(IconDeferrerImpl.java:101)
	at com.intellij.ui.DeferredIconImpl.lambda$scheduleEvaluation$2(DeferredIconImpl.java:169)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1137)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:76)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:152)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:113)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:178)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:658)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:610)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:65)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:165)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:59)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:110)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:76)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:97)
	at com.intellij.ui.DeferredIconImpl.lambda$scheduleEvaluation$5(DeferredIconImpl.java:168)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:216)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:27)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:195)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:208)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:184)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: javax.imageio.IIOException: Bad PNG signature!
	at java.desktop/com.sun.imageio.plugins.png.PNGImageReader.readHeader(PNGImageReader.java:242)
	... 48 more
2020-11-17 10:20:49,765 [ 942102]  ERROR - #com.intellij.util.ImageLoader - IntelliJ IDEA 2020.3 Beta  Build #IU-203.5784.10 
2020-11-17 10:20:49,765 [ 942102]  ERROR - #com.intellij.util.ImageLoader - JDK: 11.0.9; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o. 
2020-11-17 10:20:49,766 [ 942103]  ERROR - #com.intellij.util.ImageLoader - OS: Mac OS X 
2020-11-17 10:20:49,766 [ 942103]  ERROR - #com.intellij.util.ImageLoader - Plugin to blame: Icon Viewer 2 version: 1.3.0.193 
2020-11-17 10:20:49,766 [ 942103]  ERROR - #com.intellij.util.ImageLoader - Last Action: ChooseRunConfiguration 
2020-11-17 10:20:49,766 [ 942103]   WARN - j.iconviewer.ImageIconProvider - Error loading preview Icon - /Users/fsousa/Projects/ipb/rad/rad-server/src/main/webapp/api/images/throbber.gif 
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'image' of com/intellij/util/ui/ImageUtil.toBufferedImage must not be null
	at com.intellij.util.ui.ImageUtil.$$$reportNull$$$0(ImageUtil.java)
	at com.intellij.util.ui.ImageUtil.toBufferedImage(ImageUtil.java)
	at com.intellij.util.ui.ImageUtil.scaleImage(ImageUtil.java:219)
	at lermitage.intellij.iconviewer.ImageIconProvider.previewImage(ImageIconProvider.java:83)
	at lermitage.intellij.iconviewer.ImageIconProvider.getIcon(ImageIconProvider.java:67)
	at com.intellij.util.PsiIconUtil.getProvidersIcon(PsiIconUtil.java:17)
	at com.intellij.psi.impl.ElementBase.doComputeIconNow(ElementBase.java:87)
	at com.intellij.psi.impl.ElementBase.lambda$computeIconNow$3(ElementBase.java:83)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:127)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:116)
	at com.intellij.psi.impl.ElementBase.computeIconNow(ElementBase.java:83)
	at com.intellij.psi.impl.ElementBase.lambda$static$0(ElementBase.java:43)
	at com.intellij.ui.DeferredIconImpl.evaluate(DeferredIconImpl.java:282)
	at com.intellij.ui.DeferredIconImpl.lambda$scheduleEvaluation$1(DeferredIconImpl.java:169)
	at com.intellij.ui.IconDeferrerImpl.evaluateDeferred(IconDeferrerImpl.java:101)
	at com.intellij.ui.DeferredIconImpl.lambda$scheduleEvaluation$2(DeferredIconImpl.java:169)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1137)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:76)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:152)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:113)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:178)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:658)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:610)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:65)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:165)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:59)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:110)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:76)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:97)
	at com.intellij.ui.DeferredIconImpl.lambda$scheduleEvaluation$5(DeferredIconImpl.java:168)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:216)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:27)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:195)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:208)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:184)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by jonathanlermitage** [comment]
Confirmed with latest IJ EAP snapshot. It may be a bug in IntelliJ or the bundled JVM (no issues with IJ 2020.2), but we have a workaround: the TwelveMonkeys library can render this gif file :-)  
I will publish a new release (1.4.1) asap.

**Comment by jonathanlermitage** [comment]
@natros Can you try this release [Icon Viewer 2-1.4.1.193.zip](https://github.com/jonathanlermitage/IconViewer/files/5612783/Icon.Viewer.2-1.4.1.193.zip) ? Thx!

![install-from-zipfile](https://user-images.githubusercontent.com/857535/100552449-89466d80-3287-11eb-9214-86e3e012d626.png)

**Comment by natros** [comment]
It works without any issues. 👍

Thank you so much for this essential plugin.

**Comment by jonathanlermitage** [comment]
You're welcome :-)
